apiVersion: v1
kind: Pod
metadata:
    name: nginx
    labels:
       app: front
       app: nginx
spec:
  volumes:
    - name: index-html 
      secret: 
        secretName: secret-key
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: sensitive-secret
      volumeMounts:
        - name: index-html
          mountPath: "/usr/share/nginx/html/"
          readOnly: true
