---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-multitool-to-internet
spec:
  podSelector:
    matchLabels:
      app: multitool
      pod-template-hash: 546689b6bb
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0