apiVersion: v1
kind: Pod
metadata:
    name: nginx
    labels:
       app: front
       app: nginx
spec:
  volumes:
    - name: cm-nginx 
      configMap: 
        name: cm-nginx
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      envFrom:
          - configMapRef:
              name: cm-env
      volumeMounts:
        - name: cm-nginx
          mountPath: "/usr/share/nginx/html/"
          readOnly: true
